title: Gebrathon
author: Anónimo
logo: ../images/site/logo_gebrathon.png 

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/jucollas/Gebrathon
  branch: main

launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab"
  thebe: true

html:
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
      <img alt="Creative Commons License" style="border-width:0"
           src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" />
    </a><br />
    <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">
      Jupyter Guide to Linear Algebra
    </span> is licensed under a
    <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
      Creative Commons Attribution-NonCommercial 4.0 International License
    </a>.

sphinx:
  config:
    html_show_copyright: false
    html_theme_options:
      logo:
        text: "Gebrathon"

bibtex_bibfiles:
  - references.bib
